<?php

/**
 * Implements hook_form_alter().
 */
function google_apps_signin_form_alter(&$form, $form_state, $form_id) {

  switch ($form_id):
    case 'user_login_block':
    case 'user_login':
      $form['google_apps_link'] = array(
        '#markup' => l(t('Sign in with Google'), 'user/login/google_apps'),
        '#weight' => 10,
      );
  endswitch;
}



/*
 * Get or make a temporary folder for caching the Google what-have-yous.
 */
function _google_apps_get_temp_dir() {
  $temp_dir = variable_get('file_public_path', conf_path() . '/files/tmp');
  if (!is_dir($temp_dir)) {
    drupal_mkdir($temp_dir);
  }
  return $temp_dir;
}


/*
 * Sets the stage and redirects to Google
 */
function _google_apps_signin_login() {
  global $base_url;

  $temp_dir = _google_apps_get_temp_dir();

  // Cache for google discovery (much faster)
  $cache = new FileCache($temp_dir);

  // Open id lib has many warnig and notices
  //error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING ^ E_USER_NOTICE);

  // Login time!
  $store = new Auth_OpenID_FileStore($temp_dir);
  $consumer = new Auth_OpenID_Consumer($store);
  new GApps_OpenID_Discovery($consumer, null, $cache);

  try {
    $auth_request = $consumer->begin($_POST['domain']);
    if (!is_object($auth_request)) die('Auth request object error. Try again');
  } catch (Exception $error) {
    die($error->getMessage());
  }

  /// Request additional parameters
  $ax = new Auth_OpenID_AX_FetchRequest;
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/contact/email',2,1,'email') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/namePerson/first',1,1, 'firstname') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/namePerson/last',1,1, 'lastname') );

  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/namePerson/friendly',1,1,'friendly') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/namePerson',1,1,'fullname') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/birthDate',1,1,'dob') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/person/gender',1,1,'gender') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/contact/postalCode/home',1,1,'postcode') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/contact/country/home',1,1,'country') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/pref/language',1,1,'language') );
  $ax->add( Auth_OpenID_AX_AttrInfo::make('http://axschema.org/pref/timezone',1,1,'timezone') );

  $auth_request->addExtension($ax);

  // Request URL for auth dialog url 
  $redirect_url = $auth_request->redirectURL(
    $base_url,
    $base_url .'/user/login/google_apps/return'
  );

  if (Auth_OpenID::isFailure($redirect_url)) {
    die('Could not redirect to server: ' . $redirect_url->message);
  } else {
    drupal_goto($redirect_url);
  }	
}


/*
 * Receives the redirect from Google
 *
 */
function _google_apps_signin_return() {
  $temp_dir = _google_apps_signin_get_temp_dir();

  $store = new Auth_OpenID_FileStore($temp_dir);
  $consumer = new Auth_OpenID_Consumer($store);
  $cache = new FileCache($temp_dir);

  new GApps_OpenID_Discovery($consumer, null, $cache);

  $response = $consumer->complete($base_path . '/user/login/google_apps/return');

  // Check the response status.
  if ($response->status == Auth_OpenID_CANCEL) die('Verification cancelled.');
  if ($response->status == Auth_OpenID_FAILURE) die("OpenID authentication failed: " . $response->message);
  if ($response->status != Auth_OpenID_SUCCESS) die('Other error');

  // Successful login

  // Extract returned information
  $openid = $response->getDisplayIdentifier();
  $ax = new Auth_OpenID_AX_FetchResponse();
  if ($ax) $ax = $ax->fromSuccessResponse($response);

  $sreg = Auth_OpenID_SRegResponse::fromSuccessResponse($response);
  if ($sreg ) $sreg = $sreg->contents();

  # print response

  var_dump($openid);
  var_dump($ax_data);
  var_dump($sreg);
}

class FileCache {
  var $cache_file;

  function __construct($tmp_path) {
    $this->cache_file = $tmp_path.DIRECTORY_SEPARATOR."google.tmp";
  }

  function get($name) {
    $cache = unserialize(file_get_contents($this->cache_file));
    return $cache[$name];
  }

  function set($name, $value) {
    $cache = unserialize(file_get_contents($this->cache_file));
    $cache[$name] = $value;
    file_put_contents($this->cache_file, serialize($cache));
  }

}


